<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ru.truwlf</groupId>
    <artifactId>trueauth-velocity</artifactId>
    <version>2.3.0</version>
    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <velocity-api.version>3.4.0</velocity-api.version>
    </properties>
    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>com.velocitypowered</groupId>
            <artifactId>velocity-api</artifactId>
            <version>${velocity-api.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ru.truwlf</groupId>
            <artifactId>trueauth-proxy-common</artifactId>
            <version>2.3.0</version>
        </dependency>
    </dependencies>
    <build>
        <finalName>TrueAuth-Velocity</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <executions><execution><phase>package</phase><goals><goal>shade</goal></goals><configuration><createDependencyReducedPom>false</createDependencyReducedPom><relocations><relocation><pattern>com.zaxxer.hikari</pattern><shadedPattern>ru.truwlf.trueauth.velocity.lib.hikari</shadedPattern></relocation><relocation><pattern>org.mindrot</pattern><shadedPattern>ru.truwlf.trueauth.velocity.lib.bcrypt</shadedPattern></relocation></relocations></configuration></execution></executions>
            </plugin>
        </plugins>
    </build>
</project>
